# Generated by Django 5.1.2 on 2024-11-04 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availabilities',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('sitter_id', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('petName', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('chip_id', models.CharField(max_length=15, unique=True)),
                ('specialNeeds', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('serviceName', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=50)),
                ('petType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sitters',
            fields=[
                ('sitter_id', models.AutoField(primary_key=True, serialize=False)),
                ('sitterName', models.CharField(max_length=255)),
                ('experienceLevel', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user_id', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('role_id', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetSitterApp.pets')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetSitterApp.services')),
                ('sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetSitterApp.sitters')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetSitterApp.users')),
            ],
        ),
    ]
